//
//  MovementInput.hpp
//  LiminalSpirit
//
//  Created by Chenyu Wei on 3/2/22.
//  Copyright © 2022 Game Design Initiative at Cornell. All rights reserved.
//

#ifndef MovementInput_hpp
#define MovementInput_hpp

#include <cugl/cugl.h>
class MovementInput {
    /** Whether or not this input is active */
    bool _active;
//    /** Force generated by the left arrow key */
//    float _forceLeft;
//    /** Force generated by the right arrow key */
//    float _forceRight;
//    /** Force generated by the up arrow key */
//
//    /** The thrust produced by the keyboard only */
//    cugl::Vec2 _keybdThrust;
    
    /** x position generated by the left/right arrow key */
    float _posx;
    // TOUCH SUPPORT
    /** The initial touch location for the current gesture */
    cugl::Vec2 _dtouch;
    /** The timestamp for the beginning of the current gesture */
    cugl::Timestamp _timestamp;

protected:
    // Input results

    /** The thrust produced by the player input */
    cugl::Vec2 _inputThrust;
    
public:

#pragma mark -
#pragma mark Constructors
    /**
     * Creates a new input controller.
     *
     * This constructor does NOT do any initialzation.  It simply allocates the
     * object. This makes it safe to use this class without a pointer.
     */
    MovementInput(); // Don't initialize.  Allow stack based
    
    /**
     * Disposes of this input controller, releasing all listeners.
     */
    ~MovementInput() { dispose(); }
    
    /**
     * Deactivates this input controller, releasing all listeners.
     *
     * This method will not dispose of the input controller. It can be reused
     * once it is reinitialized.
     */
    void dispose();
    
    /**
     * Initializes the input control
     *
     * This method works like a proper constructor, initializing the input
     * controller, allocating memory and attaching listeners.
     *
     * @return true if the controller was initialized successfully
     */
    bool init();
    
    
#pragma mark -
#pragma mark Input Detection
    /**
     * Returns true if the input handler is currently active
     *
     * @return true if the input handler is currently active
     */
    bool isActive( ) const { return _active; }
    
    /**
     * Processes the currently cached inputs.
     *
     * This method is used to to poll the current input state.  This will poll
     * the keyboad and accelerometer.
     *
     * This method also gathers the delta difference in the touches. Depending
     * on the OS, we may see multiple updates of the same touch in a single
     * animation frame, so we need to accumulate all of the data together.
     */
    void update(float dt, float width, float characterWidth);
    
    /**
     * Clears any buffered inputs so that we may start fresh.
     */
    void clear();

    
#pragma mark -
#pragma mark Input Results
    /**
     * Returns the current input thrust.
     *
     * The thrust is determined by the last input method.
     *
     * @return The input thrust
     */
    const cugl::Vec2& getThrust() { return _inputThrust; }
    const float getPosx() { return _posx; }
    
    
#pragma mark -
#pragma mark Touch Callbacks
    /**
     * Callback for the beginning of a touch event
     *
     * @param t     The touch information
     * @param event The associated event
     */
    void touchBeganCB(const cugl::TouchEvent& event, bool focus);
    
    /**
     * Callback for the end of a touch event
     *
     * @param t     The touch information
     * @param event The associated event
     */
    void touchEndedCB(const cugl::TouchEvent& event, bool focus);
};

#endif
